### ISSUE TITLE
Wrong example code in README.md

### ISSUE THREAD

**Issue by mipastgt** [barbeau/earth-gravitational-model#2]
The example code given in the README.md is dangerously wrong because the lat/lon arguments to the heightOffset function are reversed.

The code must read
double offset = gh.heightOffset(lon, lat, altitudeWgs84);
and NOT
double offset = gh.heightOffset(lat, lon, altitudeWgs84);

Michael

**Comment by barbeau** [comment]
@mipastgt Whoops!  Thanks for flagging this - that's a bad one, and I'll get it fixed.

**Comment by barbeau** [comment]
@mipastgt Given that I made this error, I think others will too - so, I just refactored the method in https://github.com/barbeau/earth-gravitational-model/commit/fe6f0fd7f6643d25ac6dbf7e8de88d70f8510322 to take (lat, lon) instead of (lon, lat).

**Comment by mipastgt** [comment]
I don't think that is a good idea. The method is from GeoTools and people know that and
in the GeoTools world it is always longitude first. I also know other software which uses
your code (correctly) and your change will make all this code invalid. I would stick with
just the correction of the example.
Michael

**Comment by barbeau** [comment]
@mipastgt After thinking more about this, I agree - I just reverted the change in https://github.com/barbeau/earth-gravitational-model/commit/c641efac7f2174ac784ec8ad8b25c7d8c9a8cc6f.  So, the README is fixed to (lon, lat) and the method signature stays with the GeoTools (lon, lat) convention.

Also, thanks for letting me know that people are actually using this.  Can you share who that is?
