### ISSUE TITLE
Example in README adds instead of subtracts offset

### ISSUE THREAD

**Issue by mirko12** [barbeau/earth-gravitational-model#4]
// Add the offset to the GPS altitude to get the height above the geoid (in meters)
double altitudeMeanSeaLevel = altitudeWgs84 + offset;
This is wrong.
It should be 
// Subtract the offset from the GPS altitude to get the height above the geoid (in meters)
double altitudeMeanSeaLevel = altitudeWgs84 - offset;

**Comment by barbeau** [comment]
@mirko12 Do you have example ground-truth values I could use to write tests here (i.e., the WGS84 and mean sea level in the same location)?

I ended up not using this library myself (I used an alternate solution), so it's very possible the example is wrong (see also https://github.com/barbeau/earth-gravitational-model/issues/1 for unit tests). That being said, it would be nice to fix this up and get it into working order.

**Comment by mirko12** [comment]
I used this page to test https://geographiclib.sourceforge.io/cgi-bin/GeoidEval - and it pretty much gives the same results, at least for my area (of interest).
Your library is more precise because it takes altitude into account also. First I thought it gives wrong data, but it's only sign that is wrong (in example). Just the pure logic: if the result is geoid height _above_ WGS84 zero level - then, to get MSL you need to _subtract_ that value from WGS84 height.

**Comment by barbeau** [comment]
@mirko12 Looking at this closer, you are right, the sign needs to be changed. I've added more unit tests with known values I've observed as well. Thanks for flagging this!
